# Generated by Django 5.1.15 on 2026-05-17 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpWantedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(default='open', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('report_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='help_wanted_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'help_wanted_posts',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='HelpWantedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='help_wanted_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='classifieds.helpwantedcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classifieds.helpwantedpost')),
            ],
            options={
                'db_table': 'help_wanted_comments',
            },
        ),
        migrations.CreateModel(
            name='HelpWantedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='classifieds.helpwantedpost')),
                ('reporter', models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.CASCADE, related_name='help_wanted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_help_wanted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'help_wanted_reports',
            },
        ),
    ]
