apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storageclass-retain.yaml
  - secrets.yaml
  - mailgun-email-secret.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - redis.yaml
  - postgres.yaml
  - uploads-pvc.yaml
  - ingress.yaml
  - opensearch.yaml
  - backup-cronjob.yaml
  - indexer-cronjob.yaml
  - admin-digest-cronjob.yaml

images:
  - name: ghcr.io/smoltech/cityforge
    newTag: latest

namespace: cityforge
