---
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: cityforge-db
  namespace: cityforge
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "17"
  numberOfInstances: 1
  # maintenanceWindows:
  volume:
    size: "10Gi"
  users:
    cityforge: []
  databases:
    cityforge: cityforge
  # allowedSourceRanges:
  # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
