apiVersion: v1
kind: Service
metadata:
  name: cityforge-service
  namespace: cityforge
  labels:
    app: cityforge
    component: web
spec:
  selector:
    app: cityforge
    component: web
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
