apiVersion: v1
kind: Service
metadata:
  name: cityforge-service
  namespace: cityforge
  labels:
    app: cityforge
spec:
  selector:
    app: cityforge
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
