# Generated by Django 5.1.15 on 2026-05-17 19:16

import apps.webhooks.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.CharField(default=apps.webhooks.models._cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('events', models.TextField(help_text='JSON array of event types')),
                ('headers', models.TextField(blank=True, null=True)),
                ('retry_policy', models.TextField(blank=True, null=True)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('format', models.CharField(default='mattermost', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhook_endpoints',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.CharField(default=apps.webhooks.models._cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('data', models.TextField(help_text='JSON payload')),
                ('timestamp', models.DateTimeField()),
                ('environment', models.CharField(max_length=50)),
                ('source_info', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'webhook_events',
                'indexes': [models.Index(fields=['type', 'timestamp'], name='webhook_eve_type_5e72ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.CharField(default=apps.webhooks.models._cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('attempt', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField()),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.TextField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookevent')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='webhook_del_status_741062_idx'), models.Index(fields=['webhook_endpoint', 'created_at'], name='webhook_del_webhook_5004b8_idx'), models.Index(fields=['event_type', 'created_at'], name='webhook_del_event_t_dae0cf_idx')],
            },
        ),
    ]
