# Generated by Django 5.1.15 on 2026-05-17 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_override_url', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cards', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cards',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CardModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_override_url', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('tags_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='directory.card')),
                ('reviewer', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_modifications', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(db_column='submitted_by', on_delete=django.db.models.deletion.CASCADE, related_name='card_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_modifications',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CardSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_override_url', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('tags_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='directory.card')),
                ('reviewer', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(db_column='submitted_by', on_delete=django.db.models.deletion.CASCADE, related_name='card_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_submissions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.CASCADE, to='directory.card')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='directory.tag')),
            ],
            options={
                'db_table': 'card_tags',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(related_name='cards', through='directory.CardTag', to='directory.tag'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reported', models.BooleanField(default=False)),
                ('reported_date', models.DateTimeField(blank=True, null=True)),
                ('reported_reason', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='directory.card')),
                ('reporter', models.ForeignKey(blank=True, db_column='reported_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['card'], name='reviews_card_id_87476e_idx'), models.Index(fields=['user'], name='reviews_user_id_79db63_idx'), models.Index(fields=['hidden'], name='reviews_hidden_4f2204_idx'), models.Index(fields=['reported'], name='reviews_reporte_518b07_idx'), models.Index(fields=['created_date'], name='reviews_created_676c8f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cardtag',
            index=models.Index(fields=['tag'], name='card_tags_tag_id_a19af9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardtag',
            unique_together={('card', 'tag')},
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['name'], name='cards_name_6b179e_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['approved'], name='cards_approve_96e8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['created_date'], name='cards_created_d55878_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['approved', 'created_date'], name='cards_approve_d572e6_idx'),
        ),
    ]
