# Generated by Django 5.1.15 on 2026-05-17 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='forum_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_first_post', models.BooleanField(default=False)),
                ('report_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, db_column='edited_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_forum_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_posts',
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=280)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('report_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forums.forumcategory')),
                ('creator', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='forum_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_threads',
                'ordering': ['-is_pinned', '-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forums.forumpost')),
                ('reporter', models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.CASCADE, related_name='forum_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_forum_reports', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forums.forumthread')),
            ],
            options={
                'db_table': 'forum_reports',
            },
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forums.forumthread'),
        ),
        migrations.CreateModel(
            name='ForumCategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='forums.forumcategory')),
                ('requester', models.ForeignKey(db_column='requested_by', on_delete=django.db.models.deletion.CASCADE, related_name='forum_category_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_forum_category_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_category_requests',
                'indexes': [models.Index(fields=['status'], name='forum_categ_status_3cc8f4_idx')],
            },
        ),
    ]
