# Generated by Django 5.1.15 on 2026-05-17 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('pages_indexed', models.IntegerField(blank=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'indexing_jobs',
                'indexes': [models.Index(fields=['resource_id'], name='indexing_jo_resourc_f4f441_idx'), models.Index(fields=['status'], name='indexing_jo_status_b1a5a3_idx')],
            },
        ),
    ]
