"""Add indexes for frequently queried fields

Revision ID: e07dbcd9324c
Revises: e89963f4a481
Create Date: 2025-10-23 00:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e07dbcd9324c"
down_revision = "e89963f4a481"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add indexes to cards table
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cards_approved"), ["approved"], unique=False)
        batch_op.create_index(batch_op.f("ix_cards_created_date"), ["created_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_cards_featured"), ["featured"], unique=False)

    # Add indexes to users table
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_is_active"), ["is_active"], unique=False)

    # Add indexes to card_submissions table
    with op.batch_alter_table("card_submissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_card_submissions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_card_submissions_submitted_by"), ["submitted_by"], unique=False)

    # Add indexes to forum_threads table
    with op.batch_alter_table("forum_threads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forum_threads_category_id"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_forum_threads_created_by"), ["created_by"], unique=False)

    # Add indexes to forum_posts table
    with op.batch_alter_table("forum_posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forum_posts_thread_id"), ["thread_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_forum_posts_created_by"), ["created_by"], unique=False)

    # Add indexes to reviews table
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviews_card_id"), ["card_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_hidden"), ["hidden"], unique=False)

    # Add indexes to card_modifications table
    with op.batch_alter_table("card_modifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_card_modifications_card_id"), ["card_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_card_modifications_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes from card_modifications table
    with op.batch_alter_table("card_modifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_card_modifications_status"))
        batch_op.drop_index(batch_op.f("ix_card_modifications_card_id"))

    # Drop indexes from reviews table
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_hidden"))
        batch_op.drop_index(batch_op.f("ix_reviews_user_id"))
        batch_op.drop_index(batch_op.f("ix_reviews_card_id"))

    # Drop indexes from forum_posts table
    with op.batch_alter_table("forum_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_posts_created_by"))
        batch_op.drop_index(batch_op.f("ix_forum_posts_thread_id"))

    # Drop indexes from forum_threads table
    with op.batch_alter_table("forum_threads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_threads_created_by"))
        batch_op.drop_index(batch_op.f("ix_forum_threads_category_id"))

    # Drop indexes from card_submissions table
    with op.batch_alter_table("card_submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_card_submissions_submitted_by"))
        batch_op.drop_index(batch_op.f("ix_card_submissions_status"))

    # Drop indexes from users table
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_is_active"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    # Drop indexes from cards table
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cards_featured"))
        batch_op.drop_index(batch_op.f("ix_cards_created_date"))
        batch_op.drop_index(batch_op.f("ix_cards_approved"))

    # ### end Alembic commands ###
