"""Add IndexingJob table for indexer progress tracking

Revision ID: e89963f4a481
Revises: 7a4c8470ec66
Create Date: 2025-10-18 12:19:56.062999

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e89963f4a481"
down_revision = "7a4c8470ec66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indexing_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pages_indexed", sa.Integer(), nullable=True),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("indexing_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_indexing_jobs_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_indexing_jobs_status"), ["status"], unique=False)

    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.alter_column(
            "reported",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("false"),
        )
        batch_op.alter_column(
            "hidden",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("false"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.alter_column(
            "hidden",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("false"),
        )
        batch_op.alter_column(
            "reported",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("false"),
        )

    with op.batch_alter_table("indexing_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_indexing_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_indexing_jobs_resource_id"))

    op.drop_table("indexing_jobs")
    # ### end Alembic commands ###
