name: Mobile Build (EAS)

on:
  push:
    branches:
      - main
    paths:
      - "mobile/**"
      - ".github/workflows/mobile-build.yml"
  pull_request:
    branches:
      - main
    paths:
      - "mobile/**"
      - ".github/workflows/mobile-build.yml"
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to build"
        required: true
        type: choice
        options:
          - android
          - ios
          - all
        default: "all"
      profile:
        description: "Build profile"
        required: true
        type: choice
        options:
          - development
          - preview
          - production
        default: "preview"

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ${{ github.event_name == 'workflow_dispatch' && fromJSON(format('["{0}"]', github.event.inputs.platform == 'all' && 'android,ios' || github.event.inputs.platform)) || fromJSON('["android"]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: mobile/package-lock.json

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: mobile
        run: npm ci

      - name: Determine build profile
        id: build-profile
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_PROFILE: ${{ github.event.inputs.profile }}
        run: |
          if [ "$EVENT_NAME" == "workflow_dispatch" ]; then
            echo "profile=$INPUT_PROFILE" >> $GITHUB_OUTPUT
          elif [ "$EVENT_NAME" == "pull_request" ]; then
            echo "profile=preview" >> $GITHUB_OUTPUT
          else
            echo "profile=production" >> $GITHUB_OUTPUT
          fi

      - name: Build Android
        if: matrix.platform == 'android' || matrix.platform == 'all'
        working-directory: mobile
        run: |
          eas build --platform android \
            --profile ${{ steps.build-profile.outputs.profile }} \
            --non-interactive \
            --no-wait

      - name: Build iOS
        if: matrix.platform == 'ios' || matrix.platform == 'all'
        working-directory: mobile
        run: |
          eas build --platform ios \
            --profile ${{ steps.build-profile.outputs.profile }} \
            --non-interactive \
            --no-wait

      - name: Comment PR with build status
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 EAS build started! Check [Expo dashboard](https://expo.dev) for build status.'
            })
